-- Ownership does not rename existing tables. Backfill a deterministic order.
ALTER TABLE messages ADD COLUMN position BIGINT GENERATED BY DEFAULT AS IDENTITY;
WITH ordered AS (
    SELECT id, row_number() OVER (ORDER BY created_at, id) AS position FROM messages
)
UPDATE messages SET position = ordered.position FROM ordered WHERE messages.id = ordered.id;
ALTER TABLE messages ADD CONSTRAINT uq_message_position UNIQUE (conversation_id, position);
ALTER TABLE messages ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE product_generations ADD COLUMN history_invalidated_at TIMESTAMPTZ;
CREATE TABLE chat_message_requests (
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    request_key TEXT NOT NULL,
    input_digest TEXT NOT NULL,
    message_id UUID REFERENCES messages(id) ON DELETE SET NULL,
    PRIMARY KEY (conversation_id, request_key)
);
