"""Compatibility names for lorebook validation limits."""

from app.modules.content.lorebook.types import (
    ENTRY_CONTENT_MAX_LENGTH,
    ENTRY_METADATA_MAX_BYTES,
    ENTRY_TITLE_MAX_LENGTH,
    ENTRY_TRIGGER_MAX_COUNT,
    ENTRY_TRIGGER_MAX_LENGTH,
    LOREBOOK_DESCRIPTION_MAX_LENGTH,
    LOREBOOK_TITLE_MAX_LENGTH,
    POSTGRES_INTEGER_MAX,
    POSTGRES_INTEGER_MIN,
)

__all__ = [
    "ENTRY_CONTENT_MAX_LENGTH",
    "ENTRY_METADATA_MAX_BYTES",
    "ENTRY_TITLE_MAX_LENGTH",
    "ENTRY_TRIGGER_MAX_COUNT",
    "ENTRY_TRIGGER_MAX_LENGTH",
    "LOREBOOK_DESCRIPTION_MAX_LENGTH",
    "LOREBOOK_TITLE_MAX_LENGTH",
    "POSTGRES_INTEGER_MAX",
    "POSTGRES_INTEGER_MIN",
]
