"""Stable message ordering, retry receipts and history invalidation."""

from alembic import op

revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        "ALTER TABLE messages ADD COLUMN position BIGINT GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute("""WITH ordered AS (
        SELECT id, row_number() OVER (ORDER BY created_at, id) AS position FROM messages
    ) UPDATE messages SET position = ordered.position FROM ordered WHERE messages.id = ordered.id""")
    op.execute(
        "ALTER TABLE messages ADD CONSTRAINT uq_message_position UNIQUE (conversation_id, position)"
    )
    op.execute("ALTER TABLE messages ADD COLUMN revision INTEGER NOT NULL DEFAULT 1")
    op.execute(
        "ALTER TABLE product_generations ADD COLUMN history_invalidated_at TIMESTAMPTZ"
    )
    op.execute("""CREATE TABLE chat_message_requests (
        conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
        request_key TEXT NOT NULL, input_digest TEXT NOT NULL,
        message_id UUID REFERENCES messages(id) ON DELETE SET NULL,
        PRIMARY KEY (conversation_id, request_key)
    )""")


def downgrade():
    op.drop_table("chat_message_requests")
    op.drop_column("product_generations", "history_invalidated_at")
    op.drop_column("messages", "revision")
    op.drop_constraint("uq_message_position", "messages", type_="unique")
    op.drop_column("messages", "position")
